version: '3.9'
services:
  recipe-api:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    # restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
